apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster-claim 
spec:
  volumeName: gluster-pv
  storageClassName: slow  
  accessModes:
  - ReadWriteMany      
  resources:
     requests:
       storage: 1Gi
