apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-pv
  annotations:
    volume.beta.kubernetes.io/storage-class: slow  
spec:
  capacity:
    storage: 2Gi     
  accessModes:
  - ReadWriteMany    
  glusterfs:         
    endpoints: glusterfs-cluster 
    path: /v01 
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
